#!/bin/bash

source /opt/ros/humble/setup.bash
source ~/colcon_ws/install/setup.bash

sleep 60

export ROS_HOSTNAME=jackal
export ROS_MASTER_URI=http://jackal:11311
export ROS_HOME=~/.ros

ros2 launch roas2_bringup bringup.launch.py
